---
- name: Create Network
  hosts: localhost
  vars:
    meraki_api_key: "{{ meraki_api_key }}"
    org_id: "{{ org_id }}"
    network_name: "{{ network_name }}"

  tasks:

    - name: Default Network
      cisco.meraki.networks:
        meraki_api_key: "{{ meraki_api_key }}"
        organizationId: "{{ org_name }}"
        name: "{{ network_name }}"
        state: present
        productTypes:
          - switches
